---
toc: false
page-layout: full
listing:
  id: recipe-listings
  contents: recipes
  type: grid
  sort: "title"
  max-items: 100
  categories: true
---

# Welcome!

At this point in a personal website, you might expect to see a statistics blog. And to be fair, there are so many wonderful blogs out there covering everything from #rstats, reproducibility, and data visualization to broader questions about science and statistics.

Here, I wanted to offer something a little different. Cooking has always been my other passion. In fact, I first learned about biostatistics as a field while working in my family's restaurant, long before I knew what an academic career might look like.

So instead of a traditional blog, I hope to (semi-)frequently share recipes from my family and loved ones. These are dishes with history and stories that feel just as much a part of who I am as my research and software.

And if you have a recipe and a story you would like to share, I would love to hear it!

---

::: {#sample-listings .recipe-card-grid}
:::
